# Generated by Django 4.2.10 on 2024-06-03 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrganismTypes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('university_name', models.CharField(max_length=255)),
                ('university_short', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VariableLabelMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_name', models.CharField(max_length=100)),
                ('label_name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('char', 'CharField'), ('select', 'SelectField'), ('boolean', 'BooleanField'), ('integer', 'IntegerField'), ('email', 'EmailField'), ('file', 'FileField'), ('url', 'URLField'), ('typedchoice', 'TypedChoiceField'), ('multiplechoice', 'MultipleChoiceField'), ('typedmultiplechoice', 'TypedMultipleChoiceField')], max_length=25)),
                ('form_group', models.CharField(max_length=100)),
                ('choices', models.ManyToManyField(blank=True, to='KauffmanLabApp.choice')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('university_id', models.CharField(max_length=255)),
                ('user_short', models.CharField(max_length=255, unique=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to='KauffmanLabApp.room')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_type', models.CharField(blank=True, max_length=255, null=True)),
                ('rack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='KauffmanLabApp.rack')),
                ('room_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='KauffmanLabApp.room')),
                ('shelf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='KauffmanLabApp.shelf')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='KauffmanLabApp.storageunit')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storages', to='KauffmanLabApp.university')),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to='KauffmanLabApp.storageunit'),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('labnb_pgno', models.CharField(max_length=255)),
                ('label_note', models.CharField(max_length=255)),
                ('material_type', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_solution', models.CharField(blank=True, max_length=255, null=True)),
                ('lab_lotno', models.CharField(blank=True, max_length=255, null=True)),
                ('benchling_link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sequenced', models.BooleanField(default=False)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('genetic_modifications', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('strainname_main', models.CharField(blank=True, max_length=255, null=True)),
                ('strainname_core', models.CharField(blank=True, max_length=255, null=True)),
                ('strainname_other', models.CharField(blank=True, max_length=255, null=True)),
                ('strainname_atcc', models.CharField(blank=True, max_length=255, null=True)),
                ('strain_link', models.CharField(blank=True, max_length=255, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_purchased', models.BooleanField(default=False)),
                ('source_lotno', models.CharField(blank=True, max_length=255, null=True)),
                ('is_undermta', models.BooleanField(default=False)),
                ('source_recommendedmedia', models.CharField(blank=True, max_length=255, null=True)),
                ('organism_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.organismtypes')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.userprofile')),
                ('storage_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.storage')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='KauffmanLabApp.university'),
        ),
        migrations.AddField(
            model_name='rack',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='KauffmanLabApp.shelf'),
        ),
    ]
