# Generated by Django 4.2.10 on 2024-03-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('Sample_ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('LabNB_PgNo', models.CharField(max_length=255)),
                ('Label_Note', models.CharField(max_length=255)),
                ('Material_Type', models.CharField(max_length=255)),
                ('Parent_Name', models.CharField(blank=True, max_length=255, null=True)),
                ('Source_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('DigitalNB_Ref', models.CharField(blank=True, max_length=255, null=True)),
                ('Original_Label', models.CharField(blank=True, max_length=255, null=True)),
                ('Comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sample_Types',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sample_Type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('User_ID', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('User_Name', models.CharField(max_length=255)),
                ('University_Name', models.CharField(max_length=255)),
                ('University_ID', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BacteriaSample',
            fields=[
                ('Sample_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KauffmanLabApp.sample')),
                ('Strain', models.CharField(blank=True, max_length=255, null=True)),
                ('Species', models.CharField(blank=True, max_length=255, null=True)),
                ('ATCC_ID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalSample',
            fields=[
                ('Sample_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KauffmanLabApp.sample')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalSample',
            fields=[
                ('Sample_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KauffmanLabApp.sample')),
            ],
        ),
        migrations.CreateModel(
            name='VirusSample',
            fields=[
                ('Sample_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='KauffmanLabApp.sample')),
                ('Strain', models.CharField(blank=True, max_length=255, null=True)),
                ('Species', models.CharField(blank=True, max_length=255, null=True)),
                ('ATCC_ID', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(max_length=255)),
                ('Room_Number', models.CharField(max_length=255)),
                ('Tertiary_Storage_Type', models.CharField(max_length=255)),
                ('Tertiary_Storage_ID', models.CharField(max_length=255)),
                ('Secondary_Storage_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Secondary_Storage_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Primary_Storage_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Primary_Storage_ID', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Storage_Solution', models.CharField(blank=True, max_length=255, null=True)),
                ('Shelf', models.CharField(blank=True, max_length=255, null=True)),
                ('Sample_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KauffmanLabApp.sample')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='Sample_Type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.sample_types'),
        ),
        migrations.AddField(
            model_name='sample',
            name='User_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.user'),
        ),
    ]
