# Generated by Django 4.2.10 on 2024-06-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrganismTypes',
            new_name='OrganismType',
        ),
    ]
