# Generated by Django 4.2.10 on 2024-03-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0002_userprofile_alter_sample_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='User_Short',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
