# Generated by Django 4.2.10 on 2024-06-03 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0002_rename_organismtypes_organismtype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='name',
            new_name='rack',
        ),
        migrations.RenameField(
            model_name='shelf',
            old_name='name',
            new_name='shelf',
        ),
        migrations.RenameField(
            model_name='storageunit',
            old_name='name',
            new_name='storage_unit',
        ),
    ]
