# Generated by Django 4.2.10 on 2024-06-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0003_rename_name_rack_rack_rename_name_shelf_shelf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='university',
            new_name='university_name',
        ),
        migrations.RenameField(
            model_name='storage',
            old_name='university',
            new_name='university_name',
        ),
        migrations.RenameField(
            model_name='storageunit',
            old_name='room',
            new_name='room_number',
        ),
    ]
