# Generated by Django 4.2.10 on 2024-06-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0004_rename_university_room_university_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='university_id',
            new_name='university_short',
        ),
    ]
