# Generated by Django 4.2.10 on 2024-06-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0005_rename_university_id_userprofile_university_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organismtype',
            old_name='name',
            new_name='organism_type',
        ),
    ]
