# Generated by Django 4.2.10 on 2024-06-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0006_rename_name_organismtype_organism_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablelabelmapping',
            name='choice_id_field',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variablelabelmapping',
            name='choice_table',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variablelabelmapping',
            name='choice_text_field',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variablelabelmapping',
            name='field_required',
            field=models.BooleanField(default=False),
        ),
    ]
