# Generated by Django 4.2.10 on 2024-06-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0007_variablelabelmapping_choice_id_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablelabelmapping',
            name='choice_id_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variablelabelmapping',
            name='choice_table',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='variablelabelmapping',
            name='choice_text_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
