# Generated by Django 4.2.10 on 2024-06-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0009_sampleinserttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablelabelmapping',
            name='order_no',
            field=models.IntegerField(default=0),
        ),
    ]
