# Generated by Django 4.2.10 on 2024-06-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0010_variablelabelmapping_order_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablelabelmapping',
            name='help_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
