# Generated by Django 4.2.10 on 2024-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0012_alter_sample_storage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='is_discarded',
            field=models.BooleanField(default=False),
        ),
    ]
