# Generated by Django 4.2.10 on 2024-06-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0013_sample_is_discarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='university_short',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='university_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to='KauffmanLabApp.university'),
        ),
    ]
