# Generated by Django 4.2.10 on 2024-06-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0014_remove_userprofile_university_short_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='is_discarded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='is_purchased',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='is_sequenced',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='is_undermta',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
