# Generated by Django 4.2.10 on 2024-07-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0015_alter_sample_is_discarded_alter_sample_is_purchased_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='box',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='storage_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='KauffmanLabApp.storage'),
        ),
    ]
