# Generated by Django 4.2.10 on 2024-07-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0016_storage_box_alter_sample_storage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='host_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='host_species',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='host_strain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
