# Generated by Django 4.2.10 on 2024-07-25 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0017_sample_host_id_sample_host_species_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicalStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='is_protected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sequencing_infos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='shared_with',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='status_QC',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='status_contamination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='benchling_link',
            field=models.CharField(default='error', max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='genetic_modifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='lab_lotno',
            field=models.CharField(default='error', max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='source_lotno',
            field=models.CharField(default='error', max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='source_name',
            field=models.CharField(default='error', max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='storage_solution',
            field=models.CharField(default='error', max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='strainname_other',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variablelabelmapping',
            name='field_type',
            field=models.CharField(choices=[('char', 'CharField'), ('text', 'TextField'), ('select', 'SelectField'), ('boolean', 'BooleanField'), ('integer', 'IntegerField'), ('email', 'EmailField'), ('file', 'FileField'), ('url', 'URLField'), ('typedchoice', 'TypedChoiceField'), ('multiplechoice', 'MultipleChoiceField'), ('typedmultiplechoice', 'TypedMultipleChoiceField'), ('select2tag', 'Select2TagField')], max_length=25),
        ),
        migrations.AddField(
            model_name='sample',
            name='status_physical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.physicalstatus'),
        ),
    ]
