# Generated by Django 4.2.10 on 2024-07-25 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0018_physicalstatus_sample_is_protected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='is_discarded',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='status',
        ),
    ]
