# Generated by Django 4.2.10 on 2025-03-10 01:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('KauffmanLabApp', '0020_sample_antibiotics_sample_created_at_sample_plasmids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablelabelmapping',
            name='field_type',
            field=models.CharField(choices=[('char', 'CharField'), ('text', 'TextField'), ('select', 'SelectField'), ('boolean', 'BooleanField'), ('integer', 'IntegerField'), ('email', 'EmailField'), ('file', 'FileField'), ('url', 'URLField'), ('typedchoice', 'TypedChoiceField'), ('multiplechoice', 'MultipleChoiceField'), ('typedmultiplechoice', 'TypedMultipleChoiceField'), ('select2tag', 'Select2TagField'), ('searchmultiplechoice', 'SearchMultipleChoiceField'), ('searchsinglechoice', 'SearchSingleChoiceField')], max_length=25),
        ),
        migrations.CreateModel(
            name='DeletedSample',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('labnb_pgno', models.CharField(max_length=255)),
                ('label_note', models.CharField(max_length=255)),
                ('material_type', models.CharField(max_length=255)),
                ('host_species', models.CharField(blank=True, max_length=255, null=True)),
                ('host_strain', models.CharField(blank=True, max_length=255, null=True)),
                ('host_id', models.CharField(blank=True, max_length=255, null=True)),
                ('storage_solution', models.CharField(default='error', max_length=255)),
                ('lab_lotno', models.CharField(default='error', max_length=255)),
                ('benchling_link', models.CharField(default='error', max_length=255)),
                ('is_sequenced', models.BooleanField(blank=True, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True)),
                ('general_comments', models.TextField(blank=True, null=True)),
                ('genetic_modifications', models.TextField(blank=True, null=True)),
                ('species', models.CharField(blank=True, max_length=255, null=True)),
                ('strainname_main', models.CharField(blank=True, max_length=255, null=True)),
                ('strainname_core', models.CharField(blank=True, max_length=255, null=True)),
                ('strainname_other', models.TextField(blank=True, null=True)),
                ('strainname_atcc', models.CharField(blank=True, max_length=255, null=True)),
                ('strain_link', models.CharField(blank=True, max_length=255, null=True)),
                ('source_name', models.CharField(default='error', max_length=255)),
                ('is_purchased', models.BooleanField(blank=True, default=False, null=True)),
                ('source_lotno', models.CharField(default='error', max_length=255)),
                ('is_undermta', models.BooleanField(blank=True, null=True)),
                ('source_recommendedmedia', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.TextField(blank=True, null=True)),
                ('status_contamination', models.CharField(blank=True, max_length=255, null=True)),
                ('status_QC', models.TextField(blank=True, null=True)),
                ('shared_with', models.TextField(blank=True, null=True)),
                ('is_protected', models.BooleanField(blank=True, default=False, null=True)),
                ('sequencing_infos', models.TextField(blank=True, null=True)),
                ('plasmids', models.TextField(blank=True, null=True)),
                ('antibiotics', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('deleted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_by', to='KauffmanLabApp.userprofile')),
                ('organism_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.organismtype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.userprofile')),
                ('status_physical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='KauffmanLabApp.physicalstatus')),
                ('storage_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='KauffmanLabApp.storage')),
            ],
        ),
    ]
